CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(255) NOT NULL,
	PRODUCT_PRICE NUMBER DEFAULT 0,
	PRODUCT_STOCK NUMBER DEFAULT 999
);

<<<<<<< HEAD
SELECT * FROM TBL_PRODUCT;

-- 전체 목록
SELECT ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_STOCK
FROM TBL_PRODUCT
ORDER BY ID ASC

SELECT ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_STOCK
FROM TBL_PRODUCT
WHERE ID = 1

UPDATE TBL_PRODUCT 
SET PRODUCT_NAME = '써니의 쟁반', PRODUCT_PRICE = '50000', PRODUCT_STOCK = '20'
WHERE ID = 1
=======
SELECT * FROM TBL_PRODUCT;
>>>>>>> ffa8dc58da6d775735046839640bc2d339a2cd83
